# Generated by Django 4.0.4 on 2022-06-03 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('avatar', models.ImageField(null=True, upload_to='avatar-cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('saldo', models.IntegerField(default=0)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_telefono', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tiempo_promedio_entrega', models.IntegerField(default=30)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.cliente')),
                ('codigo', models.CharField(default=web.models.create_cod, max_length=50)),
                ('numero_productos', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('es_envio_domicilio', models.BooleanField(default=True)),
                ('costo_envio', models.IntegerField(default=0)),
                ('tiempo_entrega_estimado', models.IntegerField(default=30)),
                ('fecha_entrega_estimada', models.DateTimeField(default=web.models.pedido_espera)),
                ('es_programado', models.BooleanField(default=False)),
                ('fecha_programada', models.DateTimeField(blank=True, default=web.models.pedido_espera, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='platos')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.IntegerField(null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.restaurant')),
                ('tipo_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.tipo_menu')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.tipo_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=web.models.create_cod, max_length=50)),
                ('es_envio_domicilio', models.BooleanField(default=True)),
                ('costo_envio', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha_compra', models.DateTimeField(default=web.models.pedido_ahora)),
                ('pagado', models.BooleanField(default=False)),
                ('tiempo_entrega_est', models.IntegerField(default=30)),
                ('fecha_entrega_estimada', models.DateTimeField(default=web.models.pedido_espera)),
                ('es_programado', models.BooleanField(default=False)),
                ('fecha_programada', models.DateTimeField(blank=True, default=web.models.pedido_espera, null=True)),
                ('fecha_entregado', models.DateTimeField(blank=True, default=web.models.pedido_espera, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.tipo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(default=1)),
                ('subtotal', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.producto')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.carrito')),
            ],
        ),
    ]
