# Generated by Django 4.0.4 on 2022-06-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='num_productos',
            field=models.IntegerField(default=0),
        ),
    ]
